Submitty/RainbowGrades

constants_and_globals.h, main.cpp, output.cpp, student.cpp, student.h, zone.cpp
This addresses [#2159](https://github.com/Submitty/Submitty/issues/2159) .
A couple observations:
1. As one of the comments notes, this will use lexicographical sorting. It would be nice if the user had some way to specify the sorting to use with `make section`, perhaps this should be made into an issue as a feature request? For example consider section names "ONE", "TWO", "THREE", or "1A", "1B", "2A", "2B". There's not going to be a good "one size fits all" rule for how those should be ordered - depends on the course and instructor preference.
2. Right now it looks like no test/lab grading is happening. This is not an issue with RainbowGrades, it's how the sample course is populated. I'm not sure if that's intentional or not - does lead to very sparse output when testing. I did some …
=> Alphanumeric registration support

MakefileHelper, gradeable.h, main.cpp, output.cpp, student.cpp
Closes Submitty/Submitty#1925
Half of the work for Submitty/Submitty#2279 and Submitty/Submitty#2280 as well, the rest of the work needs to be done in the main Submitty repo. Namely, the MakefileHelper now has a target which can be used by the test script, and the Rainbow-grades side behavior for count > defined gradeables is now correct.
The other half of the work is in Submitty/Submitty#2314
=> Individual message improvements / migration to JSON

output.cpp, zone.cpp
* Students in the "null" section now have "null" printed in the `exam_seating` file
* Removed deadcode from fall 2015 for Homework 10 generation
* Times are now included in the `exam_seating` file on the first run.
* No longer crashes on a student that has an assignment but has dropped (because they now have section null). Doesn't affect existing .txt files that already are missing the section number.
=> Exam Seating Ouptut Tweaks

iclicker.cpp
Previously files were required to be named L{timestamp}.csv or L{timestamp}.xml
They can now be named L{timestamp}[any number of characters].csv/.xml so that filenames can contain more metadata, but we make sure that the timestamp is in the same place for late day calculations.
=> iClicker Filename Flexibility

MakefileHelper, main.cpp
At some point we changed how grade summary .json files represent the components. As a result the `recommendation`, `participation` and `understanding` fields in `customization.json` were being parsed but had no effect.
This PR updates the parsing so that these work again. Tested on Spring 2019 Data Structures.
=> Participation / Understanding Update for Current summary JSON Format

constants_and_globals.h, main.cpp, student.cpp
Closes Submitty/Submitty#3648
By adding `"overall_cutoff": percentage` where `percentage` is a number between 0.0 and 1.0 to a gradeable category, an instructor can now specify a minimum percentage of that category's points that must be earned by the student in order to not fail the course.
If no cutoff is provided for a given category, the cutoff is assumed to be 0.0 (no cutoff enforced).
=> Overall Grade Failure By Category Cutoff

MakefileHelper
This PR makes a few small changes to the MakefileHelper file.  The path to json_syntax_checker.py now points to the copy that resides in the main submitty repo.  This change was necessary because the script that automatically generates rainbow grades may not have permission to clone files from the web, as is the previous setup.  Moving forward anyone who wishes to manually run rainbow grades must have the main submitty repo installed on their local machine along side the RainbowGrades repo.
=> Change MakefileHelper in preparation for automatic rainbow grades generation.

MakefileHelper, main.cpp, output.cpp, table.cpp, table.h
Closes Submitty/Submitty#2659
This PR adds the capability to Rainbow Grades to generate both an output.html and output.csv for the instructor. In addition, the generation is always turned on and does not require any changes to `customization.json`.
The CSV sanitization is done based on rules set forth in RFC4180. While we could relax these rules and wrap each cell's contents in double quotes, this PR favors the simplest approach and keeping the generated CSV size down (currently a test set that created a 14MB output.html creates a 291KB output.csv). Further changes may be warranted depending on user reports and CSV behavior across the different programs that users might use to view the generated `output.csv`
Testing was done with exam seating, participation, understanding, instructor …
=> Add Automatic Generation of All Students CSV

main.cpp
closes https://github.com/Submitty/Submitty/issues/4589
When sorting names the case of the name was not ignored, so something like Zebra vanRensselaer would put Zebra first instead of second.
This issue involved 2 problems, the first was what I said above, it was not ignoring the case of the letters. However the second issue was that it was using the legal name and not the preferred name even though (at least in the way I was testing output) it was outputting the preferred name.
In the comments for the function was this `// should sort by legal name presumably (for data entry)`, I have no idea what this means, but it was put there for a reason. Git blame says @bmcutler was the person who added the comment in 2018 so maybe she can decide if there is a good reason to have it sort by legal …
=> [Bugfix] names not ignoring case when sorting

gradeable.h, main.cpp, student.cpp
This PR adds a new option at the gradeable level of the customization json, ```max_score_percentage```. When set, ```max_score_percentage``` serves as a clamp/upper bound on the maximum possible percentage that a student can receive for a gradeable type.
An example use case:
Let lab gradeables be worth 10% of a student's score for the semester.
Let us have 3 labs, each of which is worth 5% of the total after extra credit (so students can skip one lab if they do all of the extra credit for the other two).
However, we only want at most 10% of a students grade to come from labs, not 15% in the case that they do all extra credit, so we set ```max_score_percentage``` to ```0.1``` (10%).
__Questions__
1. Clamping is done in the ```GradeablePercent``` function of ```student.cpp```, which appears …
=> Add option to allow instructors to clamp maximum percentage score

output.cpp
Don't crash when attempting to take the average or standard deviation of no values.  Just return 0.
=> [Bugfix] handle array of zero values

MakefileHelper
This removes the link to mainline Submitty's json syntax checker and instead uses python's built-in [json.tool](https://docs.python.org/3/library/json.html#module-json.tool) module which does essentially the same thing as that script did when this line was added. We have not yet removed the line to deal with inline comments from the Makefile so that added capacity of `json_syntax_checker.py` is not yet used, but I believe the benefits of making this script standalone again is probably worth keeping those lines (especially given they are probably not going to be changed going forward (and have been fine for 3+ years already).
=> [Refactor:RainbowGrades] Remove usage of json_syntax_checker.py

gradeable.h, main.cpp, submini_polls.cpp
Previously the gradeable maximum was assumed to be an integer.  Now we correctly handle floating point values.
=> [Bugfix:TAGrading] floating point for gradable perfect

student.cpp
operator< was changed to fix the drop lowest feature for gradeables with different point values.
More specifically, with the previous implementation of operator<, the lowest scores were dropped regardless of the max and the percentage. It was causing the lowest absolute values of scores to always be dropped. E.g., among five scores 8/8, 8/8, 10/12, 15/30, 12/50, it would select 8/8, 8/8, and 10/12 to drop although these are the highest scores in this list if max is taken into account.
With the new implementation, this problem is fixed and the correct gradeables with the lowest scores are selected to be dropped. Following the example above, it would be 10/12, 15/30, and 12/50 for drop the lowest three.
=> [Bugfix:RainbowGrades] "drop lowest" for different point values

main.cpp
Previously the test_improvement_averaging_adjustment ignored the value specified (true/false) -- it always set it to true, now it correctly uses the value when it is set to false.
=> [Bugfix:RainbowGrades] test improvement averaging adjustment

main.cpp
The new registration_type token is breaking rainbow grades from running. This temporarily ignores the token so rainbow grades can still be run.
=> [Bugfix:RainbowGrades] Ignore registration_type token

main.cpp
Fixes an issue where a null in the user numeric id value causes rainbow grades to crash. 
Fixes submitty issue #8919 (https://github.com/Submitty/Submitty/issues/8919)
=> [Bugfix:RainbowGrades] fix issue with numeric id null value

main.cpp, output.cpp, student.h
Currently the description of all border outline is on rainbowgrades.
Students who are not related, should not see phrase such as "academic integrity violation" anywhere in their rainbowgrades.
With this change, description that are only in effect of student's rainbowgrades will be visible.
=> [Feature:RainbowGrades] Display only applied border

output.cpp, student.cpp
The current mossify function assumes average_letter_grade to be greater than 0. 
moss_penalty += -average_letter_grade * penalty;
s->getMossPenalty() < -0.01 is the threshold to check if student has moss penalty.
However, if value of average_letter_grade or penalty is 0, it does not pass the threshold and does not catch the student when displaying the black outline or adding @ to final grade.
Hence, quick fix made by increasing the default moss_penalty from
-0.0000001 -> -0.0000002
=> [Refactor:RainbowGrades] Edit Moss Default Value

student.cpp
This is student.cpp file patch by @KCony 
Mainly to address calculation of each normalized grade. 
" Grades should be compared by the normalized grade only, not normalized grade multiplied by percentages. 
Otherwise, a grade of 90 for the gradeable with percentage 0.1 will always be considered lower than a grade of 60 for the gradeable with percentage 0.2 ", which we don't want, if we were to drop lowest grade. (gradeable)
Also additional logics implemented to handle extra credit accurately. 
Additionally when running patch to default sample course, it was failing  assert(sum_percentage <= 1.0)
mostly seemed to be precision issue with floating-point arithmetic. Handled it by padding tolerance of 0.00001
Overall changes has be reviewed and tested.
However, it would be best if Barb runs it …
=> [Refactor:RainbowGrades] Student.cpp patch

constants_and_globals.h, main.cpp, output.cpp, student.cpp, student.h
Closes https://github.com/Submitty/Submitty/issues/9725
Changed all the mossify and moss instances to academic_sanction in three documents (main.cpp, student.cpp, student.h) in the Rainbow Grades directory. These changes were made to avoid potential copyright issues.
=> [Refactor: RainbowGrades] Academic sanction

main.cpp
Currently in web-based customization page, we have display option, which is acts like a switch to enable and disable contents that needs to be displayed to students. There are currently 7 options, which are available, but we will expand these features to 14 options. It is a valid checkbox on the Web GUI, but RainbowGrades cannot take the new 7 options, and will silently break if the new options are checked. Hence, this PR will fix it by adding a placeholder to handle additional tokens in display options.
=> [RainbowGrades:Feature] add display options

main.cpp
This change will allow hand written configs to accept both `academic_sanction_details` and `moss_details`
=> [Refactor:RainbowGrades] add back moss_detail

output.cpp
Certain gradeables have colored outlines to represent different statuses. Currently, the instructor gradebook does not provide a legend for these statuses. This PR adds that legend.
New Behavior:
closes [#9764](https://github.com/Submitty/Submitty/issues/9674)
=> [Feature:RainbowGrades] Adds Legend to Instructor Gradebook

main.cpp, output.cpp, student.cpp, student.h, table.cpp, table.h
Previously, no information on a student's late day exceptions were provided in rainbow grades. Now, all excused extension information is collected and stored in each student object. A row was added to the main rainbow grades table to display a student's total number of extensions, and a breakout table was added underneath the main table to display information about each individual extension. Additonally, a blue outline was added to table cell with excused extensions and text giving extension information is listed on hover.
Picture of changes to tables:
Hover Feature:
=> [Feature:RainbowGrades] Display Extensions in RainbowGrades

main.cpp, output.cpp, student.h, table.cpp, table.h
The new change will now include version conflict in request of @KCony
This is related to /Submitty/Submitty/issues/9674
And has connected PR in /Submitty/Submitty/pull/10063
If there is a conflict between TA graded version and Automated version, we call it version conflict.
The current border-outline does not indicate if it is 
One corner case I can mention is that version conflict will also count canceled submission.
=> [Feature:RainbowGrades] Version conflict borderline

submini_polls.cpp
Submini polls now feature an option to use a timer to automatically close/end the poll
https://github.com/Submitty/Submitty/pull/10184
This PR updates the parsing of the output files from generate grade summaries to handle both the old format ("status") and the new format ("end_date")
Note: The end_date does not currently contain a timestamp.  This code may need further revision if/when that is added.
=> [Bugfix:RainbowGrades] replace poll status with end_date

MakefileHelper
Currently make pull & push faces some rsync error as shown on screenshot above. 
For reference, it used to run with root, we just had to set password for submitty_daemon. 
From dev env, it is basically copying the directories, so new commands cp_pull & cp_push are introduced.
=> [Feature:RainbowGrades] Make local_pull, local_push command

MakefileHelper, RG_version.json, main.cpp, output.cpp, track_Rainbow_version.py
This update allows all users of RainbowGrades (i.e. instructors and students) to see the build version at the bottom of the RainbowGrades page. This version info is vital as it allows instructors to know which version they are currently using.
Having this version information readily available will enable instructors to provide accurate details when reporting any issues or errors they encounter. In turn, developers can use this version information to identify any potential discrepancies caused by outdated versions and assist instructors more efficiently in resolving their concerns.
[Instructor view]
[student view]
=> [Feature:RainbowGrades] Display RainbowGrades version

main.cpp
Matching behavior of Submitty Repo
=> [Refactor:RainbowGrades] Remove benchmark_percent from display
